services:
  db:
    build: ./db
    container_name: postgres-dev
    restart: unless-stopped

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: app_db

    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init.sh:/docker-entrypoint-initdb.d/init.sh
      # - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

    networks:
      - app-net

    ports:
      - "127.0.0.1:5432:5432"  # local access only

  backend:
    build: ./backend
    container_name: backend

    depends_on:
      - db

    environment:
      DATABASE_URL: postgresql://app_user:${APP_DB_PASSWORD}@db:5432/app_db

    networks:
      - app-net

    ports:
      - "8000:8000"

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: unless-stopped

    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}

    ports:
      - "127.0.0.1:5050:80"

    volumes:
      - pgadmin_data:/var/lib/pgadmin

    depends_on:
      - db

    networks:
      - app-net

volumes:
  pgdata:
  pgadmin_data:

networks:
  app-net:
    driver: bridge